name: Build Monokle-cli

on:
  workflow_dispatch: 

jobs:
  build_and_push:
    runs-on: macOS-latest


    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Package
        run: npm run package
      - name: Finn all files
        run: find .
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.4
          release_name: Release v1.0.4
          draft: false
          prerelease: false
      - name: Upload macOS amd binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/monokle-cli-macos-amd64
          asset_name: monokle-cli-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS amd binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/monokle-cli-macos-arm
          asset_name: monokle-cli-macos-arm
          asset_content_type: application/octet-stream
      - name: Upload macOS amd binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/monokle-cli-linux
          asset_name: monokle-cli-linux
          asset_content_type: application/octet-stream
      - name: Upload macOS amd binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/monokle-cli-win.exe
          asset_name: monokle-cli-win.exe
          asset_content_type: application/octet-stream
